spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  port: 8080
